baseURL = "http://MusicDataset.github.io/"
languageCode = "en-us"
title = "Music Dataset"
theme = "hugo-initio"

[taxonomies]
  composer = "composers"
  period = "periods"

[params]
    name = "Music Dataset"
    description = "A database labeling music  with descriptive tags"
    email = ""
    phone = "yiranirenewang@gmail.com"
    address = ""
    year = 2021
    avatar = "images/avatar.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/backgroud.jpg"
    favicon = "images/.png"
    DateForm = "August 3, 2021"
    author = "Irene Wang"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = false
    showClients = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "musics"
    url = "/musics/"
    weight = 2
[[menu.main]]
    name = "periods"
    url = "/periods/"
    weight = 3
[[menu.main]]
    name = "composers"
    url = "/composers/"
    weight = 4

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fab fa-facebook-square"
    footer = false
    sharethis = false
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fab fa-twitter-square"
    footer = false
    sharethis = false
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fab fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = false
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = false
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/MusicDataset"
    icon = "fab fa-github"
    footer = true
    sharethis = true
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:yiranirenewang@gmail.com"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
